name: GitHub Hosted info
on: workflow_dispatch
jobs:
  hostname-info:
    runs-on: ubuntu-latest
    steps:
      - name: Display GitHub hosted hostname info.
        run: echo "This job is running on $HOSTNAME"
